### ISSUE TITLE
Cannot run ./HTML5Setup.sh

### ISSUE THREAD

**Issue by PseudonymPatel** [UnrealEngineHTML5/Documentation#1]
Hi, I am trying to install the 4.24 HTML thing and I keep hitting barriers trying to do the HTML5Setup script. 
```
Writing .emscripten configuration file to user home directory D:\Applications\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate/
Warning: The SDK/tool 'node-12.9.1-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'python-2.7.13.1-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'java-8.152-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb49-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'sdk-releases-upstream-d57bfdd6d43181501bbd3fab502d57c9073ceb49-64bit' cannot be activated since it is not installed! Skipping this tool...
Backing up old Emscripten configuration file in D:\Applications\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate\.emscripten.old
The Emscripten configuration file D:\Applications\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate\.emscripten has been rewritten with the following contents:

NODE_JS = 'node'
TEMP_DIR = 'c:/users/sheen/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += /d/Applications/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0

Setting environment variables:
EMSDK = D:/Applications/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.0
EM_CONFIG = D:\Applications\ue4-r424-html5\Engine\Platforms\HTML5\Intermediate\.emscripten

No tools/SDKs found to activate! Usage:
   emsdk activate tool/sdk1 [tool/sdk2] [...]
** NOTICE **: The default SDK changed from `fastcomp` to `upstream`.
If you have problems, or wish to revert back to fastcomp for some other reason
you can add `-fastcomp` to explicitly install that fastcomp-based
SDK, .e.g ./emsdk install latest-fastcomp.
```
I have installed both python3.7 and 2, both from the windows store and not. I have installed node.js and I have java installed. I do not understand what I am doing wrong. I have been following the tutorial in the documentation and no errors have come up so far. Errors started when I started installing with the HTML script which used emsdk.

**Comment by PseudonymPatel** [comment]
Ok. So I changed the `EMVER` variable on line 10 of the ./HTML5Setup.sh script from 1.39.0 to 1.39.4, and I am able to get much farther into the process. There is still an error at line 113 of the script. Error message:
```
./HTML5Setup.sh: line 113: cd: /d/Applications/ue4-r424-html5/Engine/Platforms/HTML5/Intermediate/../Build/PatchFiles/emsdk-1.39.4: No such file or directory
cp: cannot stat '/d/Applications/ue4-r424-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.4/emscripten/*': No such file or directory
```

**Comment by PseudonymPatel** [comment]
For sake of completeness and for people to understand in the future, what I did to make it work was to change the name of the emsdk-1.39.0 folder inside of PatchFiles to emsdk-1.39.4 That was all that was necessary to get my thing to compile.

I was not able to finish compiling after spending about 5 hours compiling on my Ryzen 5 2600 no overclock. Let this be a warning that you need a really good pc to be able to do HTML5BuildTools. If this was not supposed to be the case, please let me know.

**Comment by nickshinpho** [comment]
it looks like you are trying to run a newer emscripten toolchain but have not run the HTML5Setup **AS-IS** first (i.e.) the _**"DO NOT IMMEDIATELY TRY TO UPGRADE ANYTHING IF THIS IS YOUR FIRST TIME HERE !!!"**_ as seen in:

- https://github.com/UnrealEngineHTML5/Documentation/blob/master/Platforms/HTML5/HowTo/README.1.emscripten.UE4.HTML5.md#first-things-first

that said:

WARNING: do NOT just change the (patch) folder name when upgrading your emscripten toolchain.  you MUST **manually inspect** to see if the "EPIC EDIT" changes (still) makes sense in the (new) file they are put in.

ALSO (just in case this is not obvious) -- you are going to STOMP on the newer file (1.39.4) with older the one (1.39.0).  this may/will cause problems when the **newer** emscripten toolchain has been updated but is running with (copied over) **older** files.

i will add a fix to the HTMLSetup script to display a warning that newer toolchain was found but no patchfiles are used if not found (which is probably where your errors are are seen in line 113 above).

**Comment by nickshinpho** [comment]
patch folder checks and verbose logging upon missing folder checked in:

- https://github.com/UnrealEngineHTML5/UnrealEngine/commit/5f8971ca198ec646c68817389bea2da567de8c77
