### ISSUE TITLE
Error finding emsdk and Node when starting HTML5Setup.sh

### ISSUE THREAD

**Issue by Forcer93** [UnrealEngineHTML5/Documentation#106]
Got an error when starting the .sh file with the lines

`error: error: tool is not installed and therefore cannot be activated: 'node-14.15.5-64bit'`
`Resolving SDK version '1.39.18' to 'sdk-releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'
`

I think that SDK refers to emsdk ...
node and emsdk as well as other dependencies are installed and can be found in console and git bash. Also system variables are all set or set by default.
Node.js version is currently 14.17, changed it to 14.15.5 64bit to match the error -> didn't work.

I also checked out this guy's guide (https://www.youtube.com/watch?v=czirUc7tJpU) but nothing helped so far.
Tried to install from cmd and with admin rights ... nothing.

It seems like the files cannot be found or the .sh struggles to resolve any of the error notes. Anybody with a tip?

**Comment by Forcer93** [comment]
Closed, because solution in older documentation showed that the emsdk folder needs to be deleted to install and activate all packages again.
After that GenerateProjectFiles.bat failed as well: Fixed it by renaming folder to older version names. Now it works!

**Comment by 1800dinky** [comment]
> Closed, because solution in older documentation showed that the emsdk folder needs to be deleted to install and activate all packages again. After that GenerateProjectFiles.bat failed as well: Fixed it by renaming folder to older version names. Now it works!

hi i know you closed this , but what exactly diid you rename to fix the generateprojecrfiles.bat - i get this error when trying to run it 

MSBUILD : error MSB1009: Project file does not exist.
Switch: Programs\UnrealBuildTool\UnrealBuildTool.csproj

GenerateProjectFiles ERROR: UnrealBuildTool failed to compile.

Press any key to continue . . .
