### ISSUE TITLE
Mac OS: Could not find file "UnrealEngine-4.24-html5/Engine/Intermediate/Build/HTML5/.emscripten"

### ISSUE THREAD

**Issue by arterror** [UnrealEngineHTML5/Documentation#115]
UATHelper: Packaging (HTML5):   ERROR: Unhandled exception: System.IO.FileNotFoundException: Could not find file "UnrealEngine-4.24-html5/Engine/Intermediate/Build/HTML5/.emscripten"

The path is incorrect, someone told I should remove the emscripten ENV value, but I don't know where is the ENV file to edit
I noticed the .emscripten is in my home folder not at "UnrealEngine-4.24-html5/Engine/Intermediate/Build/HTML5/.emscripten"

**Comment by arterror** [comment]
Someone ? Please
TX

**Comment by annachka** [comment]
My super dumb hack was to copy the emscripten folder to wherever it was looking for it. -__-

**Comment by arterror** [comment]
TX I tried that but it is asking me a .emscripten file, not a folder, what did you do exactly ?

**Comment by annachka** [comment]
I copied the emscripten folder to the path where it was expecting it, but I was on Windows.  If that's not working for you, maybe the fix is different on Mac.  :(

**Comment by arterror** [comment]
tx everything is working now, I don't know what I did but everything compiled and working now !
