### ISSUE TITLE
404 This is not the web page you are looking for

### ISSUE THREAD

**Issue by ayhama4** [UnrealEngineHTML5/Documentation#12]

**Comment by nickshinpho** [comment]
please see if the following issues will help you with the 404 error:

- https://github.com/UnrealEngineHTML5/Documentation/issues/8
- https://github.com/UnrealEngineHTML5/Documentation/issues/7

**Comment by ayhama4** [comment]
Still the same, 
I linked my accounts 2 days ago and I can not access it.

**Comment by nickshinpho** [comment]
from: https://github.com/UnrealEngineHTML5/Documentation/issues/8#issuecomment-587092613

-- begin repost --

are you signed into github?

in other words, can you see Epic's Unreal Engine repository?

- https://github.com/EpicGames/UnrealEngine

once you can see Epic's repo, you will see the HTML5 fork.

-- end of repost --

**Comment by ayhama4** [comment]
yes I am signed into GitHub and Epicgames but I can not see Epic's Unreal Engine repository

**Comment by nickshinpho** [comment]
did you check to see if your github account is connected to Epic Games Account:

- https://www.epicgames.com/account/connected

you should see something like this:

![image](https://user-images.githubusercontent.com/14188635/76438675-4d7e1780-6389-11ea-907e-46f8066a561c.png)

this is clearly written in the last section (and mentioned in every "404 error" note in the HTML5 docs that points to this page:)

- https://github.com/UnrealEngineHTML5/Documentation
-- see the very last line

please let me know where in the HTML5 docs you found this confusing.  i would like to make this a little more "obvious" since there are a few people with this problems now.

**Comment by ayhama4** [comment]
![image](https://user-images.githubusercontent.com/537635/76451164-71247a80-63e8-11ea-8507-0085584b5605.png)

**Comment by ayhama4** [comment]
now it worked

**Comment by ayhama4** [comment]
Thank you so much

**Comment by horse0291** [comment]
I'm logged in and connected and it still shows me the 404 page. any suggestions?

**Comment by avxman** [comment]
> did you check to see if your github account is connected to Epic Games Account:
> 
> * https://www.epicgames.com/account/connected
> 
> you should see something like this:
> 
> ![image](https://user-images.githubusercontent.com/14188635/76438675-4d7e1780-6389-11ea-907e-46f8066a561c.png)
> 
> this is clearly written in the last section (and mentioned in every "404 error" note in the HTML5 docs that points to this page:)
> 
> * https://github.com/UnrealEngineHTML5/Documentation
>   -- see the very last line
> 
> please let me know where in the HTML5 docs you found this confusing. i would like to make this a little more "obvious" since there are a few people with this problems now.

If for the first time you are connecting an unreal engine account in a github, do not forget to check your email for an unreal epic account, there may come an email with a confirmation link.
P.S. Sorry for my english

**Comment by horse0291** [comment]
Yes I did check that all my accounts are connected.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by nickshinpho** [comment]
(of all the days to see github go down... -- https://www.githubstatus.com/ ^ _ ^ )

@horse0291 are you able to see:

- https://github.com/EpicGames/UnrealEngine

if you can see the original (EpicGames/UnrealEngine) repo -- please double check your account linkage:

- https://www.epicgames.com/account/connected

if you can see original repo, and see your account is connected, (and github isn't down) -- you should see the ue4 html5 repo...

- https://github.com/UnrealEngineHTML5/UnrealEngine

**Comment by nickshinpho** [comment]
@horse0291 please see issue #25 helps -- i am consolidating all similar issues to that thread.

**Comment by saadya1501** [comment]
> now it worked

How it worked?

**Comment by ayhama4** [comment]
> 
> 
> > now it worked
> 
> How it worked?

apparently it needs 24 hours to work

**Comment by saadya1501** [comment]
> > > now it worked
> > 
> > 
> > How it worked?
> 
> apparently it needs 24 hours to work

okay it worked and that page is visible. How to use that respiratory in my unreal for web build.Not finding any reference,Can you tell me if any?

**Comment by rsuard** [comment]
hello, I have the same trouble here, I am connected  (since last week) but cannot access to the repo . Could you help me ?
thx
![Capture d’écran 2022-03-08 à 14 55 10](https://user-images.githubusercontent.com/32543811/157251767-29ad242b-a7e7-460e-95bd-8e88a25b3922.jpg)

**Comment by Annaati** [comment]
SomeOne I invited on a private repo had this exact error on opening the invitation link

**Comment by Giums** [comment]
> hello, I have the same trouble here, I am connected (since last week) but cannot access to the repo . Could you help me ? thx ![Capture d’écran 2022-03-08 à 14 55 10](https://user-images.githubusercontent.com/32543811/157251767-29ad242b-a7e7-460e-95bd-8e88a25b3922.jpg)

were you able to solve it?

**Comment by GoldenSlammer** [comment]
I solved it by checking Epic Games github and accepting the invitation to their organization. This invitation is sent immediately after linking your Github account to your Epic Games account.

![EpicGamesGithubInvitation](https://github.com/user-attachments/assets/914d89bc-af28-4b19-a16b-0a852dd498c9)

I'm now able to view https://github.com/SpeculativeCoder/UnrealEngine/tree/4.27-html5-es3
