### ISSUE TITLE
Unable to package project for HTML5 platform

### ISSUE THREAD

**Issue by Siphonn** [UnrealEngineHTML5/Documentation#13]
Hello, 
I have been able to downloaded and run the UnrealEngineHTML5 but when I go the package the project

- File > Package Project > HTML5

The Unreal doc for developing HTML5 Projects page opens (https://docs.unrealengine.com/en-US/Platforms/HTML5/GettingStarted/index.html).

In Project Settings - Platforms, there is no section for HTML5.

I have followed the documentation til this point (Using Git Bash, running Setup.bat, HTML5Setup.sh, GenerateProjectFiles.bat, then building UE4 with VS2017) and am unsure what to do next. 
To make sure the engine is working correctly I built the project out to windows with no issue.

Any advice on what to do next would be appreciated.

**Comment by Mosel3y** [comment]
Hi,
Check the help here:

https://github.com/UnrealEngineHTML5/Documentation/blob/master/Platforms/HTML5/HowTo/README.4.faq.UE4.HTML5.md#attempting-to-package-for-html5-instead-brings-up-the-help-page

I am also having this issue, so I will let you know when I solve it.

**Comment by Mosel3y** [comment]
@Siphonn I managed to get it packaging. I merged in Nick's changes [here](https://github.com/UnrealEngineHTML5/UnrealEngine/pull/1). 

And then I also changed the PYTHON_VER in HTMLSDKInfo.cs, to "3.7.4_64bit".
Maybe try changing that first, you might not need to merge the other changes.

After changing the version, delete Engine/Platforms/HTML5/Build/, and re-run HTML5Setup.sh & GenerateProjectFiles.bat.

**Comment by Mosel3y** [comment]
Hi @Siphonn 
This is working for me now. I started with a fresh clone of this repository.

Using git bash:

1. Run `Setup.bat`
2. Run `Engine/Platforms/HTML5/HTML5Setup.sh`
3. At this point I open `Platforms\HTML5\Source\Programs\UnrealBuildTool\HTML5SDKInfo.cs` and at line 27 change PYTHON_VER, to match the version at `Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python`, which is "3.7.4_64bit".
4. Run `GenerateProjectFiles.bat`
5. Compile engine 
6. Package Project > HTML5

Works fine.

**Comment by Siphonn** [comment]
I performed the same steps as those you listed above and was able to package to HTML5. 
Thanks you Mosel3y. I appreciate your help with this issue. 😄

**Comment by Mosel3y** [comment]
@Siphonn  Cool, glad it worked for you.

You can run it locally actually, Nick explains it [here ](https://github.com/UnrealEngineHTML5/Documentation/blob/master/Platforms/HTML5/HowTo/README.2.advanced.UE4.HTML5.md#test-html5-client-with-desktop-shootergame-host)

However since you seem to be on Pythin 3, the command is different, it's now:

`python -m http.server 8000`

If you run that command in the folder containing your packaged game, then open your browser and go to `http://localhost:8000/`, and select your html file.

**Comment by Siphonn** [comment]
@Mosel3y 
Looks like Firefox has some issues running the build but I can confirm that it works in Chrome.
Thank again.
