### ISSUE TITLE
Support with >=UE4.26

### ISSUE THREAD

**Issue by jackhwalters** [UnrealEngineHTML5/Documentation#135]
I need to build UE4.26 and above (because of dependency issues) with the HTML5 packaging feature but I can see this repository has only been updated to UE4.24.3. I'm sure there is a way of doing this, and I was wondering if anyone could give me some guidance.

**Comment by CyriaxEntertainment** [comment]
https://github.com/ufna/UnrealEngine/tree/4.27-html5_dev

**Comment by Mootbing** [comment]
I made a tutorial for 4.27 https://www.youtube.com/watch?v=vCfXeYRll_E
