### ISSUE TITLE
[Solved] Setup.bat fails with "Failed to download" message 

### ISSUE THREAD

**Issue by Mootbing** [UnrealEngineHTML5/Documentation#153]
Unreal apparently released new dependency files recently (3 weeks ago) that I think reconfigured their CDN structure.

If you are facing this issue like I was, re-download the `Commit.gitdeps.xml` file and replace the new one over the old one in `Engine/Build`

Find your version to download:
https://github.com/EpicGames/UnrealEngine/releases

**Comment by Mootbing** [comment]
https://forums.unrealengine.com/t/upcoming-disruption-of-service-impacting-unreal-engine-users-on-github/1155880

more info ^

**Comment by mikeseese** [comment]
@Mootbing Can you please close issues that are no longer an issue? People can find your issue through the search/closed issues. Keeping it open and marked `[Solved]` just clutters the Issues page of what's outstanding.
