### ISSUE TITLE
UEPlus already supports UE5.4 packaging for HTML5!

### ISSUE THREAD

**Issue by olddog618** [UnrealEngineHTML5/Documentation#164]
Latest news! UEPlus already supports UE5.4 packaging for HTML5! Supports the latest standard WebGPU.

https://www.bilibili.com/video/BV1JH4y1W7Rt/

![image](https://github.com/UnrealEngineHTML5/Documentation/assets/130716662/4724cb4d-d34e-4231-9e2e-8c237c072241)

**Comment by lcdlv** [comment]
Hi! How can I get this UEPlus?

**Comment by BitKovin** [comment]
same question

**Comment by drhouse** [comment]
same question, found this site with some info:
[https://www.uipower.com/ueplus.html](https://www.uipower.com/ueplus.html)
