### ISSUE TITLE
HTML5LaunchHelper.exe on Windows

### ISSUE THREAD

**Issue by violacambie** [UnrealEngineHTML5/Documentation#21]
hallo

I can't see the HTML5LaunchHelper.exe in the folder where files were archiveda fter building my sample project.
Following the documentasion looks like HTML5LaunchHelper is missed already during the visual studio "Compiling Support Programs" step.
![image](https://user-images.githubusercontent.com/25077324/80014571-c5834580-84d0-11ea-8af8-e2cc055aed41.png)

How can I solve this?

Many thanks

**Comment by JulienLussiez** [comment]
I got the same issue unfortunately.

**Comment by violacambie** [comment]
I ended up using the HTML5LaunchHelper.exe from a HTML5 built project made with another Unreal version  (4.23 for example). Is just used for opening a listening server on a specific port and works among different Unreal versions

**Comment by JulienLussiez** [comment]
Yes I did the same. I use 4.23 for HTML5 project but I will give it another try when the project will be updated for the 4.25 Unreal Engine version.

**Comment by nickshinpho** [comment]
can you see if this solution works:

- https://github.com/UnrealEngineHTML5/Documentation/issues/11#issuecomment-612317957

**Comment by FNGD** [comment]
It turns out the missing project file for HTML5LaunchHelper exists on Windows, it's just not included in the project. You can open and build it separately from Engine\Platforms\HTML5\Source\Programs\HTML5\HTML5LaunchHelper. Hope this helps!
