### ISSUE TITLE
LaunchURL event when trying to build to HTML5 (windows)

### ISSUE THREAD

**Issue by nooxouille** [UnrealEngineHTML5/Documentation#22]
Ok, so I am opening a new issue, instead of just replying after the issue [emsdk-1.39.0 (windows) python PATH NOT FOUND -- skipping epic patch here #20](https://github.com/UnrealEngineHTML5/Documentation/issues/20).

After successfully running the HTML5Setup.sh, I am getting 2 warnings :

![mintty_I9TcNlxQt0](https://user-images.githubusercontent.com/2682226/80112628-9bd62700-8581-11ea-9676-5dd6c2029263.png)

My python version is 3.7.7 but the warning also appeared with a newer version (3.8) and the PATH exists (and the lenghts are less than 260 char.)

![SystemPropertiesAdvanced_Yy34AP1KVa](https://user-images.githubusercontent.com/2682226/80112641-a09adb00-8581-11ea-9cd0-c3329aa83ac6.png)

Because of the "success" from the bash, I moved forward despite the warnings.
 Everything when well, until I tried to build for HTML5. When trying to build the first-person template, I am getting nothing but a redirection : a LaunchURL event happen, to this page : https://docs.unrealengine.com/en-US/Platforms/HTML5/GettingStarted/index.html

![IVUp7OGkwj](https://user-images.githubusercontent.com/2682226/80112658-a5f82580-8581-11ea-97a6-488b129fc9f8.gif)

Before that, I have tried to build for win64 and everything went well.

I am kinda lost, and I am not a UE user so I might be missing something ...

**Comment by violacambie** [comment]
I had the same problems and the HTML5 send me to the LaunchURL.
So then I made a couple of changes in the code and now the HTML5 platform works!

Try with these: in the HTML5SDKInfo.cs change the "python version" to 3.7.4 (I see from the emsdk 1.39.0 that this is the version downloaded). Plus, I have also downloaded python version 2.7.13 (since in mentioned in the code) and in the "Lib" folder (python/2.7.13.1_64bit/python-2.7.13.amd64/Lib/ ) I have copied the content of UnrealEngine/Engine/Platforms/HTML5/Build/PatchFiles/emsdk-1.39.0/python-2.7.13.1_win64only/Lib/.

With these 2 changes I have then run ./HTML5Setup.sh

You will still see the "python PATH not found error" but if you build the project, the HTML5 platform  should work in Unreal editor.
Please let me know if you can solve with this!

**Comment by nooxouille** [comment]
Unfortunatly, no, the problem remains the same.

**Comment by violacambie** [comment]
mmm..
the only things you can change more is this:

you go here: ....\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\emsdk.bat 
and change the order putting at the top of everythig the **2.7.13.1_64bit** piece of code (@IF EXIST "%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe" (
  @SET EMSDK_PY="%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe"
  @GOTO end
)
)

..this was my last change to the code..maybe help..

**Comment by nooxouille** [comment]
Hum, tbh I think the problem is somewhere else considering that "html5" do not appears as a plateform inside the project settings :/

![image](https://user-images.githubusercontent.com/2682226/80213664-cdaac480-8639-11ea-9f4b-3d77a995110f.png)

**Comment by violacambie** [comment]
yes correct.
You can't see the platform html5 until you will solve the problems before the Editor building.
I'm pretty sure is a problem of python in Windows that is not correctly seen during the installation of the UE4 Engine.
Weird because the documentation says to use python v3 but in the code is still used python2.. maybe the emsdk.bat changes could work in your case..

**Comment by Awesumson** [comment]
Did you find a fix for the Launch URL? I'm still having that issue :/

**Comment by catrujillo91** [comment]
> Hum, tbh I think the problem is somewhere else considering that "html5" do not appears as a plateform inside the project settings :/
> 
> ![image](https://user-images.githubusercontent.com/2682226/80213664-cdaac480-8639-11ea-9f4b-3d77a995110f.png)
> 
> That must be the reason of the LaunchURL event ...

Can someone please upload the ue4 cloned for html5? :( i know is a big file but i just cant solve the python problem. 
 
I get this msg when i try to run the file "generateprojectfiles"

PYTHON NOT FOUND: C:\UnrealEngine-4.24-html5\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python\2.7.13.1_64bit/python-2.7.13.amd64\python.exe
* PYTHON NOT FOUND: C:\UnrealEngine-4.24-html5\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.0\python\2.7.13.1_64bit/python-2.7.13.amd64\python.exe

Please someone can send me the ue4 v.24+++ cloned for html5?

**Comment by nickshinpho** [comment]
please see if this solution works for you:

- https://github.com/UnrealEngineHTML5/Documentation/issues/13#issuecomment-600106852
  - step 3

i will be checking in some fixes which will include that (which may be sometime next week)

**Comment by nooxouille** [comment]
> please see if this solution works for you:

Hey!
So, I tried it 2 ways : the first one was petting 3.7.4_64bits on the PYTHON_VER line.
I was still getting the python not found error. 
I compiled anyway, but got 3 errors and the compilation failed.

Then, I tried with 3.7.4-pywin32_B4bit which is the only  folder present in the emsdk-1.39.9 folder.
![image](https://user-images.githubusercontent.com/2682226/82792814-42a72f00-9e70-11ea-97db-4689ed654f1c.png)

![image](https://user-images.githubusercontent.com/2682226/82792942-72563700-9e70-11ea-9032-fdd4b7f4b44d.png)

No more errors related to the python not being found BUT, the compilation still failed, because of 3 errors again.

![image](https://user-images.githubusercontent.com/2682226/82795632-90be3180-9e74-11ea-813b-e5a8e86455a7.png)

`The MSB3073 being "..\..\Build\BatchFiles\Rebuild.bat -Target="UE4Editor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" stopped with code -1.`

**Comment by Mosel3y** [comment]
@nooxouille Hey, this isn't an issue specific to this fork I don't think. Are you using VS2019? If so, see this thread: https://forums.unrealengine.com/development-discussion/c-gameplay-programming/1738008-error-compiling-ue-4-24-1-after-updating-visual-studio-2019

**Comment by nooxouille** [comment]
Hey @Mosel3y ! I am on VS2019. Strangely, I can't remember if I have done an update these past weeks, but I remember building fine with VS2019 (except for the missing HTML5 build-option once in the engine (the root of my issue ahah).
Thanks for the link, keeping you updated

**Comment by Mosel3y** [comment]
The issue may have been fixed in a hotfix to 4.24 that isn't in this repo, I'm not sure. This seems to be the fix though: https://github.com/EpicGames/UnrealEngine/commit/25cefc81fe24c767eb995b0bb66b5611e0596973

**Comment by nooxouille** [comment]
@Mosel3y It worked ! Youhou! So the engine is running well, and I have it ready for HTML5 builds ! It seems that both your work-around and @nickshinpho fix worked!
Thx to both of you!
