### ISSUE TITLE
Error in creating UE4 Webgl project. Packaging Airsim as a plugin.

### ISSUE THREAD

**Issue by plushpluto** [UnrealEngineHTML5/Documentation#24]
I am trying to create a webgl based project for drones. Airsim (https://github.com/microsoft/AirSim) uses UE4 to simulate drones and I am trying to package Airsim as a plugin. Found your github. Followed the steps in your documentation the whole day. 

The project works when I hit Play, but fails to compile as HTML.

Got stuck with the following issue.

Plugins/AirSim/Source/AirLib/include/common/common_utils/json.hpp(95,22):  note: expanded from macro 'JSON_TRY'
[2020.04.29-14.15.21:155][461]UATHelper: Packaging (HTML5):       #define JSON_TRY try
[2020.04.29-14.15.21:155][461]UATHelper: Packaging (HTML5):                        ^

bEnableExceptions = true; is already present in AirSim.Build.cs.

Any help!

**Comment by nickshinpho** [comment]
you will need to bring this up with the AirSim plugin developers.  this is beyond the scope of HTML5 community support.
