### ISSUE TITLE
Link to: https://github.com/UnrealEngineHTML5/UnrealEngine/tree/4.24-html5/Engine/Platforms/HTML5 DOESN'T WORKING

### ISSUE THREAD

**Issue by Lars0nchik** [UnrealEngineHTML5/Documentation#25]
Hi

1) i do this: 
        Double check you are logged in to GitHub
![изображение](https://user-images.githubusercontent.com/64643067/80864561-29093200-8c8c-11ea-8a8c-7b231c2b59eb.png)

        Double check you have linked your Epic Games and GitHub accounts
![изображение](https://user-images.githubusercontent.com/64643067/80864580-548c1c80-8c8c-11ea-9dad-941bf115124f.png)

2) i do this:
        please see if the following issues will help you with the 404 error:

        #8
        #7

3) And i still see 404 error
![изображение](https://user-images.githubusercontent.com/64643067/80864596-67065600-8c8c-11ea-9c4c-9e6141ec11eb.png)

What esle should i do ?

**Comment by fllyingburritos** [comment]
I put the zip file on google drive, so you can get it here: https://drive.google.com/file/d/1LJzliloSkcF0dFm4YsNgo1Nlwy5hqtiI/view

**Comment by arcluster** [comment]
Is that ZIP file working? Downloading now

**Comment by eeench** [comment]
I just can't get this 404 error do stop showing!!! I am all linked up with the accounts, logged in, everything as required....still can't see it!!!!

**Comment by arcluster** [comment]
Hello. Make sure you accept the Email notification/invitation to join
accounts Epic games-Github

**Comment by nickshinpho** [comment]
@Lars0nchik , @eeench @arcluster are you still having problems accessing this?

please make sure you are able to also see:

- https://github.com/EpicGames/UnrealEngine/

@arcluster  - thank you for that extra detail -- i will add that to the Readme files.

**Comment by nickshinpho** [comment]
resolved in 41a5990df9e1ae564d4c978d8ee22654e4cd038b
