### ISSUE TITLE
Is this compatible with Unreal Engine 4.23.3 version?

### ISSUE THREAD

**Issue by arcluster** [UnrealEngineHTML5/Documentation#28]
I would like to know before starting the process all over again

**Comment by nickshinpho** [comment]
4.23.3 is the last "officially supported" version for HTML5 from epic.

- https://docs.unrealengine.com/en-US/Support/Builds/ReleaseNotes/4_23/index.html
  - search for **HTML5** (should be the 2nd hit) to see the notice
