### ISSUE TITLE
Does it work with the version 4.24.3?

### ISSUE THREAD

**Issue by catrujillo91** [UnrealEngineHTML5/Documentation#29]
I have a project in 4.24.3 I don't know if I will be able to export my project to html5 if i do this process to clone the ue4 4.24.0. If no, is there a way to export to html5? if i did my project in 4.24.3?

**Comment by nickshinpho** [comment]
people have had success -- and discussed in issue #14 

closing this issue -- for i will put my 4.23.3 merge progress in there (hopefully sometime next week...)
