### ISSUE TITLE
Permission denied in using HTML5Setup.sh

### ISSUE THREAD

**Issue by pavel663** [UnrealEngineHTML5/Documentation#3]
Hello.
I have a problem in firing HTML5Setup.sh.

[https://monosnap.com/file/qMb3lcMN1hGniQ21mwIGoc2BHHFwbT](https://monosnap.com/file/qMb3lcMN1hGniQ21mwIGoc2BHHFwbT)

Can you help me?

**Comment by nickshinpho** [comment]
please see if the information in this stackover flow fixes your issue:

- https://stackoverflow.com/a/57168165

**Comment by pavel663** [comment]
Thanks!

Disable python in "manage app execution aliases" and restart windows solves the problem.
