### ISSUE TITLE
Access to the UnrealEngineHTML5

### ISSUE THREAD

**Issue by pnpavlov** [UnrealEngineHTML5/Documentation#30]
Hello,

I've followed the instructions at https://github.com/UnrealEngineHTML5/Documentation/blob/master/README.md and linked my account via https://www.epicgames.com/account/connections . I've also accepted the invitation to join https://github.com/EpicGames and see the private repo https://github.com/EpicGames/UnrealEngine , but still can't see https://github.com/UnrealEngineHTML5/UnrealEngine. Can you please help me to understand what I need to do to try out the HTML5 engine? Thank you!

Regards,
Pavel

**Comment by nickshinpho** [comment]
please see if issue #25 helps
