### ISSUE TITLE
Do I have to build Unreal 4.25 myself to have access to HTML5 Platform?

### ISSUE THREAD

**Issue by kreempuff** [UnrealEngineHTML5/Documentation#31]
The docs aren't very clear. Is the only way to build for HTML5 and the web to build UnrealEngine myself?

**Comment by nickshinpho** [comment]
yes, as of 4.24 -- the only way to build for HTML5 is to use UnrealEngine Source (as opposed to UnrealEngine Launcher). 

if you're looking for status on 4.25 -- this is being tracked in #27
