### ISSUE TITLE
unreal 4.24 fatal error

### ISSUE THREAD

**Issue by 1point3** [UnrealEngineHTML5/Documentation#36]
I have spent the last 5 hours following the video https://www.youtube.com/watch?v=czirUc7tJpU and compiling the files, when I go to the UE4Editor it creates I get the error window

Fatal error:
[File:C:/UnrealEingine-4.24-html/Engine/Source/Runtime/Core/Private/Modules/Modules/ModuleManage.cpp] [Line:951]
Unable to read module manifest from
'../..//../Engine/Binaries/Win64/UE4Editor.modules'. Module manifests are generated at build time, and must be present to locate modules at runtime.

is there any links to pre built versions that I can download, and install / run? as I am on a deadline and can't afford another day lost only to get an error.

I appreciate your response.

**Comment by Mosel3y** [comment]
I have only seen that error when I need to re-compile the engine or some part of it. 

Are you on Windows? If so what version of Visual Studio are you using?
Did you get any errors when running HTML5Setup.sh

Did you follow the steps here:

https://github.com/UnrealEngineHTML5/Documentation/blob/master/Platforms/HTML5/HowTo/README.0.building.UE4.Editor.md#compiling-support-programs

1. Compile support programs
2. Then compile engine

I'm not aware of a binary version uploaded.

(Also I would recommend following the How To files in the documentation in this repo, as they are known to work. And I at least, Won't want to look through a full YouTube video to see what your workflow is. If you follow the docs here, at least we have a better idea what steps you're taking)

**Comment by 1point3** [comment]
windows 10 64bit, visual studio 2019. I can't remember any errors. but the HTML5LaunchHelper was not in the list, everythign else was.

**Comment by Mosel3y** [comment]
Do you have the changes Nick pushed yesterday updating the engine to 4.24.3?
If you're still on 4.24.0, I believe it has some issues with VS2019, I'm not certain this is the issue though.
I only have VS 2017 at the moment, which works.

**Comment by 1point3** [comment]
will download the 4.24.3 now and try

**Comment by Mosel3y** [comment]
@1point3 Also, once you have the 4.23.4 version downloaded, before you run HTML5Setup.sh, open it in a text editor and remove lines 98 - 110 inclusive. Otherwise you may get an error message, at least I do.

@nickshin On my Windows computer as of https://github.com/UnrealEngineHTML5/UnrealEngine/commit/9182b739760c255cf68c1983719a48e7628b33e6 I get the below when running HTMLSetup.sh, removing the comments fixes it.

```
Bareword found where operator expected at -e line 7, near ""simple python http server" instead"
        (Missing operator before instead?)
Bareword found where operator expected at -e line 8, near "1.emscripten"
        (Missing operator before emscripten?)
Bareword found where operator expected at -e line 11, near "@"Engine"
        (Missing operator before Engine?)
String found where operator expected at -e line 11, near "ExtraBuildProducts.Add(CommandUtils.CombinePaths(CommandUtils.CmdEnv.LocalRoot, @""
        (Missing semicolon on previous line?)
String found where operator expected at -e line 11, at end of line
        (Missing semicolon on previous line?)
syntax error at -e line 6, near "(unless"
  (Might be a runaway multi-line !! string starting on line 1)
"use" not allowed in expression at -e line 7, at end of line
Unknown regexp modifier "/t" at -e line 8, at end of line
Unknown regexp modifier "/h" at -e line 8, at end of line
Unknown regexp modifier "/b" at -e line 8, at end of line
Can't find string terminator '"' anywhere before EOF at -e line 11.
```

**Comment by nickshinpho** [comment]
@Mosel3y - thanks for finding that bug.  i've just fixed that in:

- https://github.com/UnrealEngineHTML5/UnrealEngine/commit/d637d639e41ee661d56edd456714519f5471755c

@1point3 - please also see some visual studio 2019 issues that other people have run into on UE4 (and it's not HTML5 specific):

- https://github.com/UnrealEngineHTML5/Documentation/issues?q=is%3Aissue+label%3Avs2019+is%3Aclosed
