### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by sandrobl** [UnrealEngineHTML5/Documentation#38]
I receive a 404 error when accessing: https://github.com/EpicGames/UnrealEngine

I am currently logged into GitHub and have my Unreal Account linked. 
![2020-06-05 09_10_54-Verbundene Konten](https://user-images.githubusercontent.com/32453229/83847483-9f2a0a00-a70c-11ea-96d6-52017626f224.png)

In the GitHub Application settings, there is a linked Epic App to be found.
![2020-06-05 09_12_26-Authorized OAuth Apps](https://user-images.githubusercontent.com/32453229/83847611-d993a700-a70c-11ea-8d3c-5bf528acafb6.png)

**Comment by sandrobl** [comment]
Sadly I still can't access this https://github.com/EpicGames/UnrealEngine repository.

**Comment by nickshinpho** [comment]
the only thing i can think of is: did you accept the "email confirmation link" epic sends to developers.

otherwise, you may have to contact github for further guidance:

- https://support.github.com/contact
