### ISSUE TITLE
Is an upgrade UE version expected?

### ISSUE THREAD

**Issue by pavel663** [UnrealEngineHTML5/Documentation#4]
Hello!

Current engine version - 4.24.1. Coming soon 4.24.2.
Will there be an HTML5 engine with new updates?

**Comment by nickshinpho** [comment]
sure!  i will look into merging 4.24.2 when that comes out.

**Comment by nickshinpho** [comment]
moving on 4.24.3 -- which will be tracked in issue #29

**Comment by nickshinpho** [comment]
people have had success -- and discussed in issue #14 

closing this issue -- for i will put my 4.23.3 merge progress in there (hopefully sometime next week...)
