### ISSUE TITLE
Where to add compiler tags

### ISSUE THREAD

**Issue by LTorrao** [UnrealEngineHTML5/Documentation#45]
Hi,

I  am compiling with a plugin and getting symbol errors. I get a message suggesting using "-s ERROR_ON_UNDEFINED_SYMBOLS=0"

Where can we add the html5 compiler tags such as -s USE_PTHREADS=1, etc?... I think I remember there was a file where this string of tags lived...

Thank you

**Comment by Mosel3y** [comment]
Hi, here:
https://github.com/UnrealEngineHTML5/UnrealEngine/blob/4.24-html5/Engine/Platforms/HTML5/Source/Programs/UnrealBuildTool/HTML5ToolChain.cs

**Comment by LTorrao** [comment]
Thank you @Mosel3y :)
