### ISSUE TITLE
UATHelper: Packaging (HTML5): AutomationTool exiting with ExitCode=5 (5)

### ISSUE THREAD

**Issue by msanandkumar** [UnrealEngineHTML5/Documentation#47]
I am not able to package to UE4.24 version HTML5, due to the following error, 

total log is attached, please can anyone help us? or guide me?

[HTML.txt](https://github.com/UnrealEngineHTML5/Documentation/files/4852037/HTML.txt)

**Comment by ZeusLT** [comment]
See this thread: https://github.com/UnrealEngineHTML5/Documentation/issues/5 problem is in unfinished  "HTML5Setup.sh". Something with paths and python versions.

**Comment by msanandkumar** [comment]
Hi ZeusLT, thanks for your reply, we tried many things after your suggestion, now we are having some other issue, with packaging 

I am attaching the outputlog for your reference. 


[Outputlog.txt](https://github.com/UnrealEngineHTML5/Documentation/files/4869907/Outputlog.txt)

**Comment by ZeusLT** [comment]
Sorry I can't help much with this, but you could trying to fix the syntax yourself inside `"D:/emsdk\upstream\emscripten\emcc"` `line 12` looks like there shouldn't be a comma, maybe just deleting ";" would be enough, now how it happened in a first place I have no idea.

**Comment by nickshinpho** [comment]
fixed emscripten's latest nodejs version and a bug in a patch file (thanks @cantrem404!)
