### ISSUE TITLE
Error with HTML5Setup.sh 

### ISSUE THREAD

**Issue by ckingFSS** [UnrealEngineHTML5/Documentation#54]
Running into this error while running HTML5Setup.sh:

CMake Error at C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/emscripten/emcc.bat'
  -v"! Process returned with error code 1.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
configure: cmake -G MinGW Makefiles -DBUILD_SHARED_LIBS=OFF -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE=-O2 -DNDEBUG -s WASM=1 -s WASM_OBJECT_FILES=1 -Wno-implicit-function-declaration -Wno-shift-negative-value C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/BatchFiles/ThirdParty/zlib/zlib-1.2.8 -DCMAKE_TOOLCHAIN_FILE=C:\Users\cking\Documents\GitHub\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.18\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/node/12.18.1_64bit/bin/node.exe"

Any Help would be appreciated, Im not sure what I am doing wrong,

4.24.3-html5-1.39.18

**Comment by Freaknoizer** [comment]
i got exact same error!

**Comment by nickshinpho** [comment]
fixed emscripten's latest nodejs version and a bug in a patch file (thanks @cantrem404!)
