### ISSUE TITLE
Packageing error: HTML5 No such file or directory.

### ISSUE THREAD

**Issue by ckingFSS** [UnrealEngineHTML5/Documentation#56]
Hello, 

I received this error while packageing a project file. I am unsure of what it means, Or how I am to fix. Perhaps I missed something on the initial setup?

LogPlayLevel:     [509/511] Module.Launch.cpp
LogPlayLevel:     [510/511] UE4Game.js
LogPlayLevel: Error:     emcc: error: C:\Users\cking\Documents\GitHub\UnrealEngine\Engine\Platforms\HTML5\Source\ThirdParty\PhysX3\PhysX_3.4\lib-1.39.18-up-mt\LowLevel_O2.a: No such file or directory ("C:\Users\cking\Documents\GitHub\UnrealEngine\Engine\Platforms\HTML5\Source\ThirdParty\PhysX3\PhysX_3.4\lib-1.39.18-up-mt\LowLevel_O2.a" was expected to be an 
input file, based on the commandline arguments provided)
LogPlayLevel: Took 4542.9334875s to run UnrealBuildTool.exe, ExitCode=5
LogPlayLevel: UnrealBuildTool failed. See log for more details. (C:\Users\cking\Documents\GitHub\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\UBT-UE4Game-HTML5-Development.txt)
LogPlayLevel: AutomationTool exiting with ExitCode=5 (5)
LogPlayLevel: Completed Launch On Stage: Build Task, Time: 4653.586017
LogPlayLevel: BUILD FAILED
PackagingResults: Error: Launch failed! Unknown Error

Any Help would be greatly appreciated.

4.23.18-HTML5-1.39.18

**Comment by ckingFSS** [comment]
Found This #5 :  to have the same error.  Going through initial comments and noticed I am missing PhysX_3.4 folder in …..\GitHub\UnrealEngine\Engine\Platforms\HTML5\Source\ThirdParty\PhysX3

I then attempted to ReRun the HTML5Setup.sh and got this 

+ rm -f /c/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/BatchFiles/ThirdParty/zlib/zlib-1.2.8/zconf.h
+ emcmake cmake -G 'MinGW Makefiles' -DBUILD_SHARED_LIBS=OFF -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=OFF -DCMAKE_BUILD_TYPE=Release '-DCMAKE_C_FLAGS_RELEASE=-O2 -DNDEBUG -s WASM=1 -s WASM_OBJECT_FILES=1 -Wno-implicit-function-declaration -Wno-shift-negative-value' /c/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/BatchFiles/ThirdParty/zlib/zlib-1.2.8
_**CMake Error: The source directory**_ "C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/BatchFiles/ThirdParty/zlib/zlib-1.2.8" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
configure: cmake -G MinGW Makefiles -DBUILD_SHARED_LIBS=OFF -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE=-O2 -DNDEBUG -s WASM=1 -s WASM_OBJECT_FILES=1 -Wno-implicit-function-declaration -Wno-shift-negative-value C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/BatchFiles/ThirdParty/zlib/zlib-1.2.8 -DCMAKE_TOOLCHAIN_FILE=C:\Users\cking\Documents\GitHub\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.18\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="C:/Users/cking/Documents/GitHub/UnrealEngine/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/node/12.18.1_64bit/bin/node.exe"

Not sure what I am doing wrong with this one, any help is greatly appreciated

**Comment by ZeusLT** [comment]
SetupHTML5.sh was incomplete, look at https://github.com/UnrealEngineHTML5/Documentation/issues/5#issuecomment-653133458

**Comment by ckingFSS** [comment]
Hello ZeusLT I looked at the comment, I am not sure what you mean by "If I comment out all library scripts like this in Build_All_HTML5_libs.sh"

Could you expand upon that a little more for me how to do that? 
It would greatly appreciated.
@ZeusLT

**Comment by ckingFSS** [comment]
@ZeusLT was correct commenting out all library scirpts except the PhysX resolved this issue.
