### ISSUE TITLE
Can't clone https://github.com/UnrealEngineHTML5/UnrealEngine

### ISSUE THREAD

**Issue by aboutqx** [UnrealEngineHTML5/Documentation#57]
I can clone the epic unreal, but not this. The error is `Repository not found.`

**Comment by aboutqx** [comment]
Anyone know this?

**Comment by aboutqx** [comment]
Wow
the git link works. Clone `git@github.com:UnrealEngineHTML5/UnrealEngine.git`

**Comment by roninbar** [comment]
> Wow
> the git link works. Clone `git@github.com:UnrealEngineHTML5/UnrealEngine.git`

No it doesn't...

> \> git clone git@github.com:UnrealEngineHTML5/UnrealEngine.git c:\Users\rinba\Code\UnrealEngine --progress
> ssh: Could not resolve hostname github.com: Name or service not known
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
