### ISSUE TITLE
[question] WebGL browser scripting

### ISSUE THREAD

**Issue by PabsBraz** [UnrealEngineHTML5/Documentation#6]
Hi everyone!

I've got a question. After reading the documentation, I haven't found if there is a way to directly interact with the resulting WebGL code from the Browser without tweaking WebGL code itself.

Is this possible or all interaction with Actors must be programmed pre-packaging? 

Thanks!

**Comment by nickshinpho** [comment]
this question is a little vague.  but, if you're looking to interact from the browser (i.e. outside of "game code" and via javascript) to the "game code" (i.e. c++ engine code) -- yes, this is possible.  and yes, this can only be done via programming pre-packaging (to make it easy for you access/traverse the UE4 objects).

taking a look at: 
- https://github.com/UnrealEngineHTML5/UnrealEngine/tree/4.24/Engine/Platforms/HTML5/Source/Runtime/HTML5/HTML5JS

you can see the JS functions wrapped up in the `UE_JavascriptLibrary` object and this can be accessed via c++ that are exposed in the` extern "C"` headers.

those files (`HTML5JavaScriptFx.{.h,.js}`) shows how to:

- from C++ calling JS functions (basically everything in the `extern "C"` .h file)
- from JS calling C++ function (see `UE_GSystemResolution` and `UE_EngineRegisterCanvasResizeListener` in the .js file)

hope this helps.

**Comment by PabsBraz** [comment]
It does indeed @nickshinpho. That's exactly what I was looking for. Thanks for the help and sorry for not being more specific in my first question. 

Cheers!

**Comment by ZeusLT** [comment]
I have very similar question, but the opposite of this one, is it possible to relay commands from inside the game to the browser running the game, for example I want to make ingame "fullscreen" button and remove/hide the html one so I do not have to deactivate the game frame to go fullscreen.
