### ISSUE TITLE
What are the default Pluggins for HTML5 Editor?

### ISSUE THREAD

**Issue by ckingFSS** [UnrealEngineHTML5/Documentation#61]
Hello,

I *foolishly* removed a bunch of what I thought were un-needed plugins from the HTML5 editor I built.

Now I am starting to run into errors that i haven't encountered before upon packaging a project.

I was wondering if anyone had a list of the pluggins that come default when the HTML5 engine is built?

Thank you for all of your help

4.24.3-HTML5-1.39.18

**Comment by ckingFSS** [comment]
This is the error that I am getting

UATHelper: Packaging (HTML5):     [471/473] Module.Launch.cpp
UATHelper: Packaging (HTML5):     [472/473] UE4Game-HTML5-Shipping.js
UATHelper: Packaging (HTML5):     emcc:INFO: NOTE: linking HTML5 project -- this takes at least 7 minutes (and up to 20 minutes on older machines) to complete.
UATHelper: Packaging (HTML5):     emcc:INFO:       we are workig with the Emscripten makers to speed this up.
UATHelper: Packaging (HTML5):     **wasm-ld: error: 'atomics' feature is used by NpAggregate.cpp.o, so --shared-memory must be used**
UATHelper: Packaging (HTML5):     **emcc: error: 'C:/HTML/ue4/UnrealEngine/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/bin\wasm-ld.exe @C:\HTML\ue4\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.18\tmp\emscripten_qjhrctoi.rsp' failed (1)
PackagingResults: Error: 'atomics' feature is used by NpAggregate.cpp.o, so --shared-memory must be used
PackagingResults: Error: 'C:/HTML/ue4/UnrealEngine/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/bin\wasm-ld.exe @C:\HTML\ue4\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.18\tmp\emscripten_qjhrctoi.rsp' failed (1)**
UATHelper: Packaging (HTML5): Took 5544.7472251s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (HTML5): UnrealBuildTool failed. See log for more details. (C:\HTML\ue4\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\UBT-UE4Game-HTML5-Shipping.txt)
UATHelper: Packaging (HTML5): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (HTML5): BUILD FAILED
PackagingResults: Error: Unknown Error

Any Idea what i did to cause this? I was able to package successfully before i messed with the plugins.

**Comment by Muchaszewski** [comment]
To fix `wasm-ld: error: 'atomics' feature is used by NpAggregate.cpp.o, so --shared-memory must be used` enable multi-threaded support in HTML5 Project settings:
![image](https://user-images.githubusercontent.com/5092066/91302750-3ef4b280-e7a7-11ea-8a08-cb5345267071.png)
