### ISSUE TITLE
Setup.bat "Path not found"

### ISSUE THREAD

**Issue by OtisSchwarze** [UnrealEngineHTML5/Documentation#66]
When i open setup.bat it just says path not found

**Comment by Mosel3y** [comment]
How are you trying to open it, in git bash?
type ./Setup.bat
Notice the "./"

And make sure you are in the folder that contains Setup.bat

**Comment by OtisSchwarze** [comment]
> How are you trying to open it, in git bash?
> type ./Setup.bat
> Notice the "./"
> 
> And make sure you are in the folder that contains Setup.bat

I Tried It but it still says path not found :(
