### ISSUE TITLE
Datasmith C4D importer not working.

### ISSUE THREAD

**Issue by taufiq-dev** [UnrealEngineHTML5/Documentation#76]
I've enabled the Datasmith Content, Datasmith Importer and Datasmith C4D Importer plugins. The first two are required for the C4D Importer plugin. When I click the Datasmith button, it only accepts .udatasmith file format and no .c4d file format to be found. Is this a known issue?

**Comment by ZeusLT** [comment]
This is probably not html5 branch related, but make sure you have all of the datasmith plugins required enabled, here is a quick video I've found: https://www.youtube.com/watch?v=MZHAQ40kXuc

**Comment by taufiqsun** [comment]
Hmm it still doesn't work... All other Datasmith plugins work except for C4D

**Comment by taufiq-dev** [comment]
I did a hacky way by installing the original UE 4.24.3 through epic launcher, enabled the plugin there, and migrate the imported c4d datasmith file into this html version of UE 4.24.3.
