### ISSUE TITLE
can not open https://github.com/UnrealEngineHTML5/UnrealEngine/tree/4.24-html5/Engine/Platforms/HTML5

### ISSUE THREAD

**Issue by liangxiaoshan520918** [UnrealEngineHTML5/Documentation#8]
can not open " https://github.com/UnrealEngineHTML5/UnrealEngine/tree/4.24-html5/Engine/Platforms/HTML5"

**Comment by nickshinpho** [comment]
please see issue #7 and the **NOTE:** section in:

- https://github.com/UnrealEngineHTML5/Documentation

in other words, (before you are able to see this HTML5 fork) you need to be able to see the original epic unreal engine repository:

- https://github.com/EpicGames/UnrealEngine
