### ISSUE TITLE
Error 'atomics' feature is used by NpAggregate.cpp.o  HTML5 build faild on the end ....

### ISSUE THREAD

**Issue by zlatnaspirala** [UnrealEngineHTML5/Documentation#84]
I have nice working all build targets (win .linux android html5) also dedicated server works on win and linux !
  Great but after CHANGES:

  I change multi thread in html5 settings bar. 
  Also i added isLocallyControlled node in BP.

  After that there is no any way to build success HTML5 client part.
  Already rebuild ue4.24.3 .
  
Error log:
```
Severity Code Description Project File Line Suppression State
Error 'atomics' feature is used by NpAggregate.cpp.o, so --shared-memory must be used Brm C:\Zlatnaspirala\active-projects\rocket-craft\rocket-craft\versions\4.24.3\BrmModern\Intermediate\ProjectFiles\wasm-ld 1

Severity Code Description Project File Line Suppression State
Error 'C:/Applications/unreal-source/ue4/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/bin\wasm-ld.exe @C:\Applications\unreal-source\ue4\Engine\Platforms\HTML5\Build\emsdk\emsdk-1.39.18\tmp\emscripten_bzu9800w.rsp' failed (1) Brm C:\Zlatnaspirala\active-projects\rocket-craft\rocket-craft\versions\4.24.3\BrmModern\Intermediate\ProjectFiles\emcc 1
```

I found that file NpAggregate.cpp in PhysX folder.
 
I try emcc clear cache also rebuild all.....

Any suggestion?

Here is the critical project : 

https://github.com/zlatnaspirala/rocket-craft

Is it real good idea to delete Intermediate vs. ans Saved folder and make it all again.....

**Comment by Mootbing** [comment]
did you fix this by reenabling mutithreaded support? It seems like that is needed to build properly
