### ISSUE TITLE
HTML5Setup.sh error

### ISSUE THREAD

**Issue by Summber01** [UnrealEngineHTML5/Documentation#86]
I get this error when I run html5setup.sh: $ ./HTML5Setup.sh
$ ./HTML5Setup.sh
./HTML5Setup.sh: line 24: cmake: command not found
May I ask how to solve this problem

**Comment by Summber01** [comment]
I'm sorry I didn't install it ahead of time Cmake ,The issue has been resolved.

**Comment by KunalBhorodiya** [comment]
I get  "**Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.**" When I run **./HTML5Setup.sh** I have python 3.8 installed in my system...

Any solution ???
