### ISSUE TITLE
Error in Running html5setup. sh file

### ISSUE THREAD

**Issue by thomasbergersen** [UnrealEngineHTML5/Documentation#87]
./HTML5Setup.sh: line 277: syntax error: unexpected end of file

**Comment by kroegen** [comment]
@thomasbergersen how did you resolve this issue?
I am myself not a great shell script coder, can't find what is causing the problem.
Actually the whole file a little bit messy.

**Comment by kroegen** [comment]
For everyone who is looking for solution check here: https://github.com/UnrealEngineHTML5/Documentation/issues/69
