### ISSUE TITLE
Pack html5 error

### ISSUE THREAD

**Issue by thomasbergersen** [UnrealEngineHTML5/Documentation#88]
UATHelper: 正在打包 (HTML5): AutomationTool exiting with ExitCode=5 (5)
PackagingResults: Error: Unhandled exception: System.IO.FileNotFoundException: Could not find file "/Users/Shared/Epic_Games/UnrealEngine-4.24-html5/Engine/Intermediate/Build/HTML5/.emscripten"
UATHelper: 正在打包 (HTML5): RunUAT ERROR: AutomationTool was unable to run successfully.
PackagingResults: Error: AutomationTool was unable to run successfully.
PackagingResults: Error: Unknown Error

**Comment by mollymun** [comment]
Hi thomasbergersen,

I am having the exact same error. I am assuming you have closed this because you fixed it, what was the solution? If you could let me know it would help so much! Thanks!

**Comment by arterror** [comment]
Hi thomasbergersen,

Same for me how did you resolved "Could not find file "/Users/Shared/Epic_Games/UnrealEngine-4.24-html5/Engine/Intermediate/Build/HTML5/.emscripten"

**Comment by SaurabhKumbhar24** [comment]
Has anyone resolved this problem

**Comment by zlatnaspirala** [comment]
I have this error too. All you need to remove emscripten ENV values. Every env value related to the emscripten. 
 After this i got healty builds.

**Comment by arterror** [comment]
@**zlatnaspirala** TX very much, could you be more specific, what file should I modify ? 
And what should I write exactly ?, TX

**Comment by arterror** [comment]
@zlatnaspirala "All you need to remove emscripten ENV values", please where do I remove that ? thanx

**Comment by zlatnaspirala** [comment]
For windows users :

 
![env-for-windows](https://user-images.githubusercontent.com/3426783/140647977-ed749bc7-60fd-44b2-8fdf-97a8f71008c1.png)

Remove any EMSCRIPTEN paths .
You can also uninstall emsdk if you have it - Or simple change root folder name to OLD-emsdk to make it unabable 

I am not sure for 100% but this is list [for system env vars]

```
NODE_JS 
LLVM_ROOT 
BINARYEN_ROOT 
EMSCRIPTEN_ROOT 
```

If oyu find EMSCRIPTEN_ROOT  in system env remove it ....
