### ISSUE TITLE
ERROR: Unable to find a valid installation of Visual Studio.

### ISSUE THREAD

**Issue by MarkAckerley** [UnrealEngineHTML5/Documentation#89]
Hi,

I followed the listed steps, I have Visual Studio 2019 installed, I tried following the post about installing on Windows 10, but nothing has worked.

Any advice would be appreciated.

Thanks,

Mark

"GenerateProjectFiles ERROR: Unable to find a valid installation of Visual Studio.  Please check that you have Visual Studio 2017 or Visual Studio 2019 installed, and the MSBuild component is selected as part of your installation."

![image](https://user-images.githubusercontent.com/41670424/110811385-8f80b880-827e-11eb-8f43-dcb10d4914e4.png)

**Comment by MarkAckerley** [comment]
It was necessary to install the Visual Studio C++ components to make this work.

**Comment by danilobuendia** [comment]
Which ones? I followed the doc, no luck.

**Comment by seb-the-architect** [comment]
Same here, no luck. I have MSBuild installed too...

**Comment by Ares9323** [comment]
> Which ones? I followed the doc, no luck.

Installing "Desktop development with C++" from the Visual Studio Installer solved the issue for me:
![image](https://user-images.githubusercontent.com/46932745/200965099-f8aaac56-462b-4c2e-98df-29e8815bec81.png)
